name: Master Workflow - Build and deploy to production
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  pull_request:
    types: closed
    branches:
      - master
      - develop
      - "releases/**"
jobs:
  build:
    name: Core Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - run: |
        console.log("hello world")
